
CREATE TABLE public.history_ohlc ( id int8 DEFAULT nextval('daily_price_id_seq'::regclass) NOT NULL,
trade_date date NOT NULL,
code varchar(12) NOT NULL,
"open" NUMERIC(14, 2) NULL,
high NUMERIC(14, 2) NULL,
low NUMERIC(14, 2) NULL,
"close" NUMERIC(14, 2) NULL,
previous NUMERIC(14, 2) NULL,
"change" NUMERIC(14, 2) NULL,
remarks varchar(5) NULL,
volume int8 NULL,
value NUMERIC(20, 2) NULL,
freq int4 NULL,
best_bid_price NUMERIC(14, 2) NULL,
best_bid_volume int8 NULL,
best_offer_price NUMERIC(14, 2) NULL,
best_offer_volume int8 NULL,
"date" varchar(50) NULL,
CONSTRAINT daily_price_pkey PRIMARY KEY (id),
CONSTRAINT daily_price_trade_date_code_key UNIQUE (trade_date,
code));